
-- CLAUSULA WHERE - NOS SIRVE PARA FILTRA O BUSCAR DETERMINADOS REGISTROS POR DETERMINADOS VALORES

SELECT * FROM Paciente WHERE idPais = 'ARG' -- NOS DEVULEVE TODOS LOS RESULTADOS QUE TENGAN ESA COINCIDENCIA

SELECT * FROM Paciente WHERE apellido = 'Paredes'

SELECT * FROM Paciente WHERE idpaciente = 5

SELECT * FROM Paciente WHERE fNacimiento = '2019-02-18' -- también se puede poner '20190218'