
-- FUNCIONES MAX Y MIN - NOS PERMITER OBTENER EL VALOR MÁXIMO Y MÍNIMO DE UN CAMPO

SELECT * FROM Pago

SELECT MAX (fecha) FROM Pago -- OBTENEMOS LA FECHA MÁS RECIENTE

SELECT MIN (monto) FROM Pago -- OBTENEMOS EL MONTÓ MÁS CHICO 

-- APARTE DE LOS CAMPOS CON FECHAS Y MONTOS TAMBIEN SE PUEDE USAR EN CAMPOS TIPO VARCHAR EN ORDEN ALFABETICO