
-- FUNCION HAVING - TRABAJAN CONJUNTAMENTE CON LA FUNCIÓN COUNT Y GROUP BY 
-- HAVING (DONDE EL VALOR SEA ...) SE DIFERENCIA DEL WHERE EN QUE EL WHERE FILTRA EN UN REGISTRO EN PARTICULAR
-- EN CAMBIO EL HAVING FILTRA SOBRE UN CONJUNTO DE REGISTROS, UTILIZA EL GROUP BY POR QUE DEVUELVE UN RESULTADO
-- EN FUNCIÓN A UN GRUPO DE REGISTROS 

SELECT * FROM Turno

SELECT estado FROM Turno GROUP BY estado HAVING COUNT(estado) = 2 -- OBTENEMOS COMO RESULTADO LOS REGISTROS QUE TENGAN 2 ESTADOS

SELECT estado FROM Turno GROUP BY estado HAVING COUNT(estado) >= 2