
-- FUNCION SUM - NOS PERMITE REALIZAR UNA SUMATORIA DE DETERMINADO CAMPO NUMERICO

SELECT * FROM Pago

SELECT SUM(monto) FROM Pago -- OBTENEMOS LA SUMA DE TODOS LOS MONTOS REGISTRADOS

-- USO DE ALIAS DE CAMPO
SELECT SUM(monto) AS montoTotal FROM Pago -- NOS GENERA UN NOMBRE DE COLUMNA CON EL RESULTADO 

-- SUMARLE VALOR AL RESULTADO 
SELECT SUM(monto + 20) AS montoTotal FROM Pago -- LE SUMA 60 POR QUE LE SUMA 20 A CADA MONTO DEL REGISTRO

-- SUMAR UN VALOR AL TOTAL DEL RESTULTADO
SELECT SUM(monto) + 20 AS montoTotal FROM Pago 