

-- FUNCION AVG - OBTENER UN PROMEDIO DE TODOS LOS DATOS DONDE HACEMOS LA CONSULTA

SELECT * FROM Pago 

SELECT AVG(monto) AS montoPromedio FROM Pago -- OBTENEMOS EL PROMEDIO DE LA SUMATORIA DE TODOS LOS MONTOS DIVIDIO POR LA CANTIDAD

-- A DIFERENCIA DE LA FUNCIÓN SUM ES INDIFERENTE CUALQUIERA DE LAS DOS FORMAS DA EL MISMO RESULTADO
-- SUMARLE UN VALOR A CADA UNO DE LOS MONTOS
SELECT AVG(monto + 20) AS montoPromedio FROM Pago

-- SUMARLE UN VARLO AL TOTAL 
SELECT AVG(monto) + 20 AS montoPromedio FROM Pago