

-- FUNCION COUNT 
SELECT * FROM Paciente

SELECT COUNT(*) FROM Paciente -- NOS CUENTA LA CANTIDAD DE FILAS QUE TIENE LA TABLA

-- CONTAR UN DATO ESPECIFICO 
SELECT COUNT(*) AS apellidosParedes FROM Paciente WHERE apellido = 'Paredes'