
-- CONDICIONAL IF - NOS SIRVE PARA EVALUAR EL VALOR DE UNA CONSULTA Y EJECTUAR ACCIONES 

DECLARE @idpaciente int 
DECLARE @idturno int
SET @idpaciente = 5

IF @idpaciente = 7
BEGIN  -- INICIA EL BLOQUE DE INSTRUCCIONES PARA EL CONDICIONAL IF
		SET @idturno = 20
		SELECT * FROM Paciente WHERE idpaciente = @idpaciente
		PRINT @idturno
		PRINT @idpaciente
END -- FINALIZA EL BLOQUE DE INSTRUCCIONES PARA EL CONDICIONAL IF
ELSE 
BEGIN
	PRINT 'NO SE CUMPLIO LA CONDICION'
END

