
-- CONDICIONAL CASE 

DECLARE @valor int
DECLARE @resultado char(10) = ''
SET @valor = 20

SET @resultado = (CASE WHEN @valor = 10 THEN 'ROJO'
						WHEN @valor = 20 THEN 'VERDE'
						WHEN @valor = 30 THEN 'AZUL'
						ELSE 'NO HAY COINCIDENCIA'
					END)

PRINT @resultado

-- USAMOS UNA CONSULTA SELECT CON UN CASE PARA AGREGAR A LA CONSULTA - EL ELSE ES EN CASO QUE NO SE CUMPLA NINGÚN CASE
SELECT *, (CASE WHEN estado = 1 THEN 'VERDE' ELSE 'GRIS' END) AS COLOR_TURNO FROM Turno