
-- ESTRUCTURA TRY CATCH

DECLARE @CONTADOR INT = 0



BEGIN TRY
	SET @CONTADOR = 'TEXTO' -- GENERA UN ERROR DEL TIPO DE DATO 
END TRY 

BEGIN CATCH -- EN CASO DE ERROR EN TIEMPO DE EJECUCIÓN LO ATRAPA EL CATCH Y EJECTUA 
	PRINT 'NO ES POSIBLE ASIGNAR UN TEXTO A UN TIPO INT'
END CATCH
