
-- INSTRUCCIONES RETURN Y BREAK

DECLARE @CONTADOR INT = 0

-- RETURN
WHILE @CONTADOR <= 10
BEGIN
	PRINT @CONTADOR
	SET @CONTADOR += 1
	IF @CONTADOR = 3
		RETURN -- ESTO CORTA LA EJECUCIÓN Y SALE DEL BUCLE DE MANERA FORZADA
END
PRINT 'SIGUE EL PROGRAMA' -- ESTO NO SE EJECUTA POR QUE SE CORTA LA EJECUCIÓN DEL PROGRAMA CON EL RETURN

-- BREAK

DECLARE @CONTADOR1 INT = 0


WHILE @CONTADOR1 <= 10
BEGIN
	PRINT @CONTADOR1
	SET @CONTADOR1 += 1
	IF @CONTADOR1 = 3
		BREAK -- ESTO HACE SALIR DEL CICLO Y SIGUE LA EJECUCIÓN DEL PROGRAMA
END
PRINT 'SIGUE EL PROGRAMA' -- ESTO SE IMPRIME YA QUE EL BREAK SOLO SALE EL CICLO 