
-- OPERADOR BETWEEN - NOS PERMITE FILTRAR LOS REGISTROS POR UN DETERMINADO RANGO DE FECHAS, NUMEROS O TEXTOS

SELECT * FROM Turno

-- FILTRAMOS POR FECHA
SELECT * FROM Turno WHERE fechaTurno BETWEEN '2019-01-02' AND '2019-01-06' -- OBTENEMOS LOS REGISTROS EN ESE RANGO DE FECHA

-- FILTRAMOS POR NUMERO
SELECT * FROM Pago WHERE monto BETWEEN 4000 AND 7000 -- OBTENEMOS LOS REGISTROS QUE ESTAN ENTRE ESOS MONTOS


